
set(MC_COMMON_SRC ${MC_TOP_DIR}/src)

add_definitions("-DUSE_MONOCYPHER
-DED25519_CUSTOMHASH
-DED25519_TEST
-DED25519_NO_INLINE_ASM
-DED25519_FORCE_32BIT")

# USE recursive search to add all libsodium files.
file(GLOB_RECURSE MONOCYPHER_REC_SRC
  ${MC_COMMON_SRC}/*.c
)

set(MONOCYPHER_SRC
    ${MONOCYPHER_REC_SRC}
    ${MC_TOP_DIR}/LibraryFiles.cmake
)

list(REMOVE_DUPLICATES MONOCYPHER_SRC)
